steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'infrastructure/docker/Dockerfile.cloudrun'
      - '-t'
      - 'gcr.io/$PROJECT_ID/lab-lens-web:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/lab-lens-web:latest'

images:
  - 'gcr.io/$PROJECT_ID/lab-lens-web:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
